In [346]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


# view & copy

In [347]:
import numpy as np

In [348]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [349]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [350]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [351]:
org

array([  0,   1, 200,   3,   4])

In [352]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [353]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [354]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [355]:
org

array([0, 1, 2, 3, 4])

In [356]:
x = np.arange(6)


In [357]:
y = x.reshape(2,3) # view를 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [358]:
y.base


array([0, 1, 2, 3, 4, 5])

In [359]:
z.base

array([20, 21, 22, 23, 24, 25])

In [360]:
c = z.copy()
print(c.base)

None


# nadarray의 보기로 같은 구조만 수정 가능

In [361]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [362]:
lst[3:5] = [30,40,50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [363]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [364]:
x[3:5] = [30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

# 보기와 얕은 복사

In [365]:
a = np.array([[1,2,3] , [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [366]:
b = a 
b is a

True

In [367]:
print(id(a))
print(id(b))

2532869234032
2532869234032


In [368]:
print(b.base)

None


In [369]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [370]:
v = a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [371]:
print(id(a))
print(id(v))

2532869234032
2532869233456


In [372]:
v[0,1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [373]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

# 브로드캐스팅 개요와 간단 연산

In [374]:
from numpy import array

a = array([3,4,5])
b = array([8,7,6])
a+b

array([11, 11, 11])

In [375]:
a = array([3,4,5,7])
b = array([8,7,6,])
a* b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

# 스칼라 또는 단일 값과 배열의 연산

In [ ]:
from numpy import array
a = array([3,4,6])
a

array([3, 4, 6])

In [ ]:
b = 2
b

2

In [ ]:
a+b

array([5, 6, 8])

In [ ]:
from numpy import array
A = array([[1,2,3], [1,2,3]])
A

In [ ]:
A+2

# 2차원 배열의 브로드캐스팅

In [ ]:
from numpy import arange
x = arange(1,10).reshape(3,3)

In [ ]:
y = arange(-1.2)
y

array([], dtype=float64)

In [ ]:
x * y

In [ ]:
x+y

In [ ]:
from numpy import arange
x =  arange(1,10).reshape(3,3)

In [ ]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [ ]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [ ]:
x - y

# 행 또는 열이 1인 두배열의 브로드캐스팅

In [ ]:
from numpy import arange
x = arange(1,4)


In [ ]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [ ]:
x * y

In [ ]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [ ]:
from numpy import arange
x = arange(0,10,3).reshape(4,1)

In [ ]:
y = arange(1,3)
y

array([1, 2])

In [ ]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [ ]:
x+y

# 상수 np.newaxis 활용해 두 배열의 브로드캐스팅

In [ ]:
from numpy import array

x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [ ]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [ ]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [ ]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
a.shape

(4, 1)

In [ ]:
from numpy import array
b = array([1,2,3])
b

array([1, 2, 3])

In [ ]:
b

array([1, 2, 3])

In [ ]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
a * b

In [ ]:
x*y

# 고급 인덱싱

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [ ]:
print(x[[2]])
print(x[[2,3]])

[2]
[2 3]


In [ ]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [ ]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [ ]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

# 2차원 배열의 색인

In [ ]:
from numpy import arange
x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[[0],[1]]

array([1])

In [ ]:
x[:, [5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [ ]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[[1,3],:]

In [ ]:
x[[1,3] , [2,2]]

In [ ]:
x[[1,3], [2]]

In [ ]:
x[[1,3], [3,3]]

In [ ]:
x[[1,3],[3]]

array([11, 27])

In [ ]:
from numpy import array
x[array([0,2,4]), array([0,1])]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
x[np.array([0,2,4]),1]


array([ 1, 17, 33])

In [ ]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

# 다양한 모양의 배열 색인

In [ ]:
from numpy import arange
a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4 , 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

# 고급 색인 방법

In [ ]:
a[arange(2,4)]


array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[arange(2,4)[:,[1,0]]]

In [ ]:
a[arange(2,5)[:,1,0,3,5]]

In [ ]:
a[arange(2,5)[:,arange(-1,-8,-1)]]

# 05주 수업
# (1)배열 결합
# 과학용 컴퓨팅 패키지 numpy 라이브러리

In [2]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
c = np.arange(20,24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [ ]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [ ]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [ ]:
d = np.array([100,200])
np.vstack((a,d))

In [ ]:
d = np.array([100,200,300])
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
import numpy as np
x = np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
import numpy as np
a = np.arange(6).reshape(3,2)

# hstack()

In [3]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [4]:
np.hstack((a,b))


array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
c = np.array([[10,20] , [30,40]])
c

array([[10, 20],
       [30, 40]])

In [ ]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
np.hstack((np.arange(3), np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

# 배열 결합 연산 column_stack(tup),  tup:  1차원 배열

In [ ]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
np.column_stack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x[:, np.newaxis]

In [ ]:
y[:, np.newaxis]

In [ ]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:, np.newaxis] , y[:, np.newaxis]))


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.hstack((x,y))


array([ 1,  2,  3, 10, 20, 30])

# row_stack()

In [ ]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a,b))

C:\Users\109-1\AppData\Local\Temp\ipykernel_5116\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
a = np.array([4.,2.,1.])
b = np.array([3.,8.,7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


C:\Users\109-1\AppData\Local\Temp\ipykernel_5116\1818014301.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a,b)))


In [ ]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
np.row_stack == np.vstack

False

# 배열 결합 연산  concatenate()와  stack()

In [ ]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

# axis :  int , optional

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [8]:
import numpy as np
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [6]:
z = np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [9]:
np.concatenate((x,y))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [11]:
print(np.hstack(x,y,z))
print(np.column_stack(x,y,z))
print(x,y,z)

TypeError: hstack() takes 1 positional argument but 3 were given

In [ ]:
np.concatenate((x,y,z))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.concatenate((x,y) , axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.concatenate((x,y,z) , axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.concatenate((x,y) , axis=None)

#  stack()

In [ ]:
import numpy as np 
a= np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [ ]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a,b) , axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a,b) , axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.arange(6).reshape(2,3)
x

In [ ]:
y = np.arange(10,16).reshape(2,3)
y

In [ ]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax0 = np.stack((x,y,z) , axis=0)
ax0

ValueError: all input arrays must have the same shape

In [ ]:
ax0.shape

NameError: name 'ax0' is not defined

In [ ]:
ax1 = np.stack((x,y,z) , axis=1)

ValueError: all input arrays must have the same shape

In [ ]:
ax0.shape

In [ ]:
print('np.stack(x,y,z) axis=0')
print(np.stack(x,y,z) axis=0)
print('np.stack(x,y,z) axis=-1')
print(np.stack(x,y,z) axis=-1)
print('np.stack(x,y,z) axis=2')
print(np.stack(x,y,z) axis=2)

In [ ]:
ax2 = np.stack((x,y,z) , axis=2)
ax2

ValueError: all input arrays must have the same shape

In [ ]:
ax0.shape

In [ ]:
x

In [ ]:
x[:, : ,  np.newaxis]

In [ ]:
np.expand_dims(x, axis=2)

In [ ]:
y

In [ ]:
y[:, :, np.newaxis]

In [ ]:
z

In [ ]:
np.expand_dims(z,axis=2)

In [ ]:
np.stack((x,y,z) , axis=2)

# np.stack()

In [ ]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = np.arange(1,6,2)
c

array([1, 3, 5])

In [ ]:
c[:, np.newaxis]


array([[1],
       [3],
       [5]])

In [ ]:
np.hstack((a,c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.hstack((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
np.hstack((a, np.expand_dims(c, axis=1)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 3 dimension(s)

In [ ]:
np.column_stack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
np.c_[b ,c]

# row_stack()과 vstack()

In [ ]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [ ]:
np.row_stack((a,b))

In [ ]:
np.vstack((a,b))

# np.c_[]와 np.column_stack()

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [13]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [17]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [ ]:
np.c_[x,y]

In [ ]:
np.column_stack((x,y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 8 and the array at index 1 has size 2

In [ ]:
np.c_[x , 10 , 20 , y]

In [ ]:
np.column_stack[x,10,20,y]

# np.r_[]

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.r_[a,b]

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.row_stack((a,b))

C:\Users\109-1\AppData\Local\Temp\ipykernel_5116\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [ ]:
np.r_[3:10:3 , [0]*2 , 5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [ ]:
np.r_[-1:1:6j , [0]*2 , 5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [ ]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

# np.r_['i,j,k',a,b]

In [ ]:
a = np.array([[0,1,2] , [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['0' , a , a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.r_['-1' , a ,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.r_['-1', a ,a]

In [18]:
np.r_['0,2' , [1,2,3], [4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.r_['0,3' , [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
np.r_['0,3,0' , [1,2,3], [4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [ ]:
np.r_['0,3,0' , [1,2,3], [4,5,6]].shape

(6, 1, 1)

In [ ]:
np.r_['0,3,1' , [1,2,3], [4,5,6]].shape

In [ ]:
np.r_['0,3,2' , [1,2,3], [4,5,6]]

# 1차원 배열 , 벡터의 다양한 결합 방법 

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape)
print(b.shape)

(3,)
(3,)


In [ ]:
np.hstack((a,b))

In [ ]:
np.r_[a,b]

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# 여러 1차원 배열을 수직 방향으로 합치는 방법

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape)
print(b.shape)

In [ ]:
np.hstack((a,b))

In [ ]:
np.row_stack((a,b))

In [ ]:
np.r_[a[np.newaxis, :] , b[np.newaxis , :]]


In [ ]:
np.r_['0,2' , a, b]

In [ ]:
np.concatenate((a[np.newaxis, :] , b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

# 여러 1차원 배열을 행으로 확장해 수평 방향으로 합치는 방법

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape)
print(b.shape)

In [ ]:
np.column_stack((a,b))

In [ ]:
np.hstack((a[:, np.newaxis] , b[:, np.newaxis]))


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.r_['1,2,0' , a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.concatenate(((a[:, np.newaxis] , b[: , np.newaxis])) , axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

# 기본 함수 split()

# np.split(ary,n)

In [ ]:
import numpy as np
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
s = np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
print(type(s))
print(s[0])

<class 'list'>
[0. 1. 2.]


In [ ]:
np.split(x,4)

ValueError: array split does not result in an equal division

# np.split(ary , [i,j,k, ...])

In [ ]:
x = np.arange(1,10)
x

In [ ]:
np.split(x , [2,6])

[array([0., 1.]), array([2., 3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
y = np.arange(10,61,10)
y

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.split(y,  [2,3,4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [ ]:
np.split(y , [2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [ ]:
x[4:6]

array([4., 5.])

In [ ]:
y[6:]

array([], dtype=int64)

# 다차원 배열 np.hsplit(ary , n)

In [ ]:
a = np.arange(24).reshape(2,12)
a

In [ ]:
np.split(a,3,axis=1)

In [ ]:
np.split(a,4, axis=1)

IndexError: tuple index out of range

In [ ]:
np.split(a,5, axis=1)

In [ ]:
np.split(a, [3,5,7] , axis=1)

In [ ]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b,3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.split(b, [2,4,6] , axis=0)

# 분할 함수 hsplit()과 vsplit()

# np.hsplit(ary)

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
np.hsplit(a, [2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.hsplit(a,4)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
np.hsplit(a,5)

In [ ]:
np.hsplit(a, (3,5,8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
a[:, :3]

In [ ]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

# np.vsplit(ary)

In [ ]:
a = np.arange(10)
a

In [ ]:
np.vsplit(a,2)

In [ ]:
a = np.arange(18).reshape(6,3)
a

In [ ]:
np.vsplit(a,3)

In [ ]:
np.vsplit(a,4)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [ ]:
np.vsplit(a, (1,4,6))

ValueError: vsplit only works on arrays of 2 or more dimensions

In [ ]:
a[:1, :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
a[4:6 , :]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
a[6:, :]

# 3차원 배열의 hsplit()

In [ ]:
x = np.arange(32).reshape(4,4,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x,2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [ ]:
np.split(x,2,axis=1)

In [ ]:
x[:, :2, :]

In [ ]:
x[:, 2:, :]

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])

In [ ]:
np.hsplit(x , [1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

# 3차원 배열의 vsplit()

In [ ]:
x = np.arange(32).reshape(4,4,2)
x

In [ ]:
np.vsplit(x,2)

In [ ]:
np.split(x,2, axis=0)

In [ ]:
x[:2 , :, :]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [ ]:
x[2: , :, :]

array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [ ]:
np.vsplit(x, [1,3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

# 분할 함수 array_split()

In [ ]:
import numpy as np
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
np.array_split(x,2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [ ]:
np.array_split(x,3)

In [ ]:
np.array_split(x,4)

In [ ]:
np.array_split(x,5)

# 2차원 np.aray_split() 분할

In [ ]:
import numpy as np
a = np.arange(35).reshape(7,5)
a

In [ ]:
np.array_split(a,2,axis=0)

In [ ]:
np.array_split(a,2,axis=1)

IndexError: tuple index out of range

In [ ]:
np.array_split(a,4, axis=0)

[array([3]), array([4]), array([5]), array([7])]

In [376]:
np.array_split(a,4,axis=1)

IndexError: tuple index out of range

In [ ]:
np.array_split(a, [2,4] , axis=0)

In [ ]:
np.array_split(a, [2,4] , axis=1)

# 3차원 이상에서 axis=2로 배열 분할

# np.array_split(a, axis=2)

In [ ]:
import numpy as np
x = np.arange(24).reshape(2,2,6)

In [ ]:
np.array_split(x,4, axis=2)

In [ ]:
np.split(x , [2,4,5] , axis=2)

In [ ]:
x[:, :, 5:]

# 함수 np.dsplit()

In [377]:
import numpy as np
x = np.arange(24).reshape(2,2,6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [ ]:
np.dsplit(x,2)

In [378]:
np.split(x,2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [379]:
np.dsplit(x,3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [380]:
np.dsplit(x,4)

ValueError: array split does not result in an equal division

In [381]:
np.dsplit(x,[2,4,5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [382]:
x[:, :, 4:5]

array([[[ 4],
        [10]],

       [[16],
        [22]]])

# numpy의 난수와 다양한 함수

In [383]:
import numpy as np
rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x24DBAA56F80

# 난수 제너레이터의 함수 random(), integers()

In [384]:
r = rg.random()
r

0.22733602246716966

In [385]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

# 난수 생성기 함수 integers()

In [387]:
import numpy as np
rg = np.random.default_rng(12345)
r = rg.integers(low = 0 , high=10 , size=3)
r

array([6, 2, 7])

In [ ]:
rg.integers(1,7,(3,4))

# 난수 제너레이터의 함수 standarad_normal()

In [389]:
import numpy as np
rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [388]:
rg.standard_normal((4,3))

array([[-0.87066174, -0.25917323, -0.07534331],
       [-0.74088465, -1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306,  2.34740965],
       [ 0.96849691, -0.75938718,  0.90219827]])